steps:
  - name: maven:3-jdk-8
    entrypoint: mvn
    args: ["clean","install"]
  - name: maven:3-jdk-8
    entrypoint: mvn
    args: ["package", "-Dmaven.test.skip=true"]
  - name: gcr.io/cloud-builders/docker
    args: ["build", "-t", "gcr.io/1/cb-covid19", "--build-arg=JAR_FILE=target/cb-covid19-1.0.0.jar", "."]
images: ["gcr.io/1/cb-hackathon"]
